### ISSUE TITLE
Vigilante 8 Segment

### ISSUE THREAD

**Issue by ImanCol** [Random06457/Z64Utils#60]
Support extract fs Vigilante 8 & Vigilante 8 Seccond Offense
![image](https://user-images.githubusercontent.com/26169049/234707058-30258446-aba2-4666-a67f-c819e90df1ce.png)

**Comment by Random06457** [comment]
Hi, unfortunately this repository works only with video games that use the zelda engine. Which as far as I know only includes Ocarina of Time, Majora's Mask and Animal Crossing.
The reason for that is that Nintendo 64 game engines work too differently and have a lot of flexibility over the format in which assets/filesystems are stored inside a ROM.
Therefore Adding support for these games would be out of scope for this project as the assets would not be compatible.
